### ISSUE TITLE
AspectJ LTW Problem

### ISSUE THREAD

**Issue by jundl77** [intellimate/Izou#41]
Some problem at loading addons (here from the lib folder within target and trying to load the new sdk with debug addon)

CONSOLE: 

```java
Connected to the target VM, address: '127.0.0.1:56747', transport: 'socket'
2015-06-05 14:22:50,068 DEBUG [main] org.intellimate.izou.main.Main (Main.java:90) - Starting Izou
2015-06-05 14:22:50,070 DEBUG [main] org.intellimate.izou.main.Main (Main.java:91) - Initializing...
2015-06-05 14:22:50,354 DEBUG [main] org.intellimate.izou.main.Main (Main.java:111) - Done initializing.
2015-06-05 14:22:50,355 DEBUG [main] org.intellimate.izou.main.Main (Main.java:112) - Adding addons..
2015-06-05 14:22:51,342 DEBUG [main] org.intellimate.izou.main.Main (Main.java:127) - retrieving addons & registering them
2015-06-05 14:22:51,345 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:91) - searching for addons in: /Users/julianbrendl/Google Drive/Programming/Java/Izou/target/lib
2015-06-05 14:22:51,408 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:94) - loading plugins
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced/MixerAspect.class'
[WeavingURLClassLoaderHelper] warning bad library: 'file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar!/javax/sound/sampled/AudioSystem.class'
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced/MixerAspect.class'
[WeavingURLClassLoaderHelper] warning bad library: 'file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar!/javax/sound/sampled/AudioSystem.class'
2015-06-05 14:22:51,997 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:96) - loaded: [PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.sdk, pluginClass=org.intellimate.izou.sdk.ZipFileManagerImpl, version=0.7.0, provider=intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou, pluginVersion=null]]], pluginPath=/sdk-0.7.0], PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.debugaddon, pluginClass=org.intellimate.izou.debugaddon.ZipFileManager, version=1.0.0, provider=org.intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou.sdk, pluginVersion=0.0.0]]], pluginPath=/debugaddon-1.0]]
2015-06-05 14:22:51,997 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:100) - starting plugins
2015-06-05 14:22:52,173 ERROR [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:103) - Error while trying to start the PF4J-Plugins
java.lang.NullPointerException
	at java.net.URLStreamHandler.sameFile(URLStreamHandler.java:394) ~[?:1.8.0_20]
	at java.net.URL.sameFile(URL.java:894) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.lambda$checkAndWeave$2(IzouPluginClassLoader.java:113) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader$$Lambda$15/1988939205.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_20]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_20]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_20]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_20]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.checkAndWeave(IzouPluginClassLoader.java:146) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClass(IzouPluginClassLoader.java:77) ~[pf4j-1.7.1.jar:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_20]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_20]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_20]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_20]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_20]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_20]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_20]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_20]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClassFromClasses(IzouPluginClassLoader.java:215) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadCustomClass(IzouPluginClassLoader.java:163) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClass(IzouPluginClassLoader.java:102) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:43) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:63) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManager.java:224) ~[pf4j-1.7.1.jar:?]
	at org.intellimate.izou.addon.AddOnManager.loadAddOns(AddOnManager.java:101) [classes/:?]
	at org.intellimate.izou.addon.AddOnManager.retrieveAndRegisterAddOns(AddOnManager.java:45) [classes/:?]
	at org.intellimate.izou.main.Main.<init>(Main.java:128) [classes/:?]
	at org.intellimate.izou.main.Main.<init>(Main.java:60) [classes/:?]
	at org.intellimate.izou.main.Main.main(Main.java:136) [classes/:?]
2015-06-05 14:22:52,225 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:106) - retrieving addons from the plugins
2015-06-05 14:22:52,233 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:108) - retrieved: []`

**Comment by LeanderK** [comment]
can you format your issue next time?

**Comment by LeanderK** [comment]
should be moved to pf4j

**Comment by LeanderK** [comment]
commit c70e9ec6741affde9b572a8fed51cd919f77a611 should fix it

**Comment by jundl77** [comment]
This issue is still there, I think nothing changed, but I'll post the log anyway: 

```java
Connected to the target VM, address: '127.0.0.1:57922', transport: 'socket'
2015-06-10 09:05:15,481 DEBUG [main] org.intellimate.izou.main.Main (Main.java:90) - Starting Izou
2015-06-10 09:05:15,484 DEBUG [main] org.intellimate.izou.main.Main (Main.java:91) - Initializing...
2015-06-10 09:05:15,879 DEBUG [main] org.intellimate.izou.main.Main (Main.java:111) - Done initializing.
2015-06-10 09:05:15,908 DEBUG [main] org.intellimate.izou.main.Main (Main.java:112) - Adding addons..
2015-06-10 09:05:17,149 DEBUG [main] org.intellimate.izou.main.Main (Main.java:127) - retrieving addons & registering them
2015-06-10 09:05:17,171 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:92) - searching for addons in: /Users/julianbrendl/Google Drive/Programming/Java/Izou/target/lib
2015-06-10 09:05:19,092 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:95) - loading plugins
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%20Drive/Programming/Java/Izou/file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar!/javax/sound/sampled'
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%20Drive/Programming/Java/Izou/file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar!/javax/sound/sampled'
2015-06-10 09:05:19,434 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:97) - loaded: [PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.sdk, pluginClass=org.intellimate.izou.sdk.ZipFileManagerImpl, version=0.7.0, provider=intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou, pluginVersion=null]]], pluginPath=/sdk-0.7.0], PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.debugaddon, pluginClass=org.intellimate.izou.debugaddon.ZipFileManager, version=1.0.0, provider=org.intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou.sdk, pluginVersion=0.0.0]]], pluginPath=/debugaddon-1.0]]
2015-06-10 09:05:19,435 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:101) - starting plugins
2015-06-10 09:05:19,456 ERROR [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:104) - Error while trying to start the PF4J-Plugins
java.lang.NullPointerException
	at java.net.URLStreamHandler.sameFile(URLStreamHandler.java:394) ~[?:1.8.0_20]
	at java.net.URL.sameFile(URL.java:894) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.lambda$checkAndWeave$2(IzouPluginClassLoader.java:113) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader$$Lambda$15/275056979.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_20]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_20]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_20]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_20]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_20]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.checkAndWeave(IzouPluginClassLoader.java:146) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClass(IzouPluginClassLoader.java:77) ~[pf4j-1.7.1.jar:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_20]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_20]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_20]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_20]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_20]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_20]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_20]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_20]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_20]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClassFromClasses(IzouPluginClassLoader.java:215) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadCustomClass(IzouPluginClassLoader.java:163) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.IzouPluginClassLoader.loadClass(IzouPluginClassLoader.java:102) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:43) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:63) ~[pf4j-1.7.1.jar:?]
	at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManager.java:224) ~[pf4j-1.7.1.jar:?]
	at org.intellimate.izou.addon.AddOnManager.loadAddOns(AddOnManager.java:102) [classes/:?]
	at org.intellimate.izou.addon.AddOnManager.retrieveAndRegisterAddOns(AddOnManager.java:46) [classes/:?]
	at org.intellimate.izou.main.Main.<init>(Main.java:128) [classes/:?]
	at org.intellimate.izou.main.Main.<init>(Main.java:60) [classes/:?]
	at org.intellimate.izou.main.Main.main(Main.java:136) [classes/:?]
2015-06-10 09:05:19,465 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:107) - retrieving addons from the plugins
2015-06-10 09:05:19,476 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:109) - retrieved: []
```

**Comment by jundl77** [comment]
Also now addOns are in /target/lib and not /lib, is there a way to change it back to lib?

**Comment by LeanderK** [comment]
should be fixed
